EVAL_BASE_ID="";//考核任务ID
EVAL_NAME="";//考核名称
START_DATE="";//个人总结填报开始时间
END_DATE="";//个人总结填报结束时间
STATUS="";//考核状态
EVAL_STATUS = "进行中";
HAVE_SCORE_LIST="";//是否已生成评分表格
IS_EMT_UNDERWAY=false;//判断是否有进行中的考核任务true/false
EVAL_SCOPE = "";//考核范围
ID = "";
SCOPE = "";
MANAGE_TYPE_DATA="";
MONTH_PER_TERM="";
TERM_DATA="";
Class_TIME_1TERM = "";//第一学期上课时间
Class_TIME_2TERM = "";//第二学期上课时间
VACATION_TIME = "";//轮休时间
WORK_DAYS = "";//年度上班天数
PROJECT_NAME_DATA ="";
YJS_EDU_TYPE_DATA ="";
CLASS_TIME="";
TEACH_CALCULATE_DATA = "";//课堂教学计周学时条件
COUESE_TYPE_DATA ="";//课程类型备注
